### ISSUE TITLE
An exception occurred: HTTP could not register URL http://+:8000/

### ISSUE THREAD

**Issue by MehdiAnis** [SitholeWB/MT5WCFHTTPService#4]
I am getting this error

An exception occurred: HTTP could not register URL http://+:8000/. Your process does not have access rights to this namespace (see http://go.microsoft.com/fwlink/?LinkId=70353 for details).

I will appreciate some guide to get this useful project running. Thanks.

**Comment by SitholeWB** [comment]
Run Visual Studio as Administrator, I hope that you will help you.

**Comment by MehdiAnis** [comment]
Thank you very much, it worked. Now I think I  need the How-To-Use instructions. I already posted a New Issue. If you happen to have the instructions/steps and share here that will be great. I am not sure if the mt4api web site will ever come back.
