### ISSUE TITLE
How To Page doesn't exist : http://mtapi4.net/how-to-use/

### ISSUE THREAD

**Issue by MehdiAnis** [SitholeWB/MT5WCFHTTPService#5]
"The first step will be to follow the Metatrader 5 instructions from http://mtapi4.net/how-to-use/"

However this page doesn't exist. The whole website is down, as of now. Can anyone please share the How-To-Use instructions here. Thank you.

**Comment by SitholeWB** [comment]
Hi, I have added _How-To-Use instructions_ on wiki, it a copy that was taken from http://mtapi4.net/how-to-use/

The wiki is at https://github.com/SitholeWB/MT5WCFHTTPService/wiki

Hope it helps

**Comment by MehdiAnis** [comment]
Awesome! Many thanks. I kind of figured it out and tried last night. It worked.
